# This is a basic workflow to help you get started with Actions

name:  Hourly Build

# Controls when the workflow will run
on:
  schedule:
    - cron: '1 * * * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      # Runs a single command using the runners shell
      - name: generate txt
        env:
          CHATGPT_ENGINE: ${{ secrets.CHATGPT_ENGINE }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make weather

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: info change 
